/**
 * Design Token Values & CSS Variable Mapping
 * packages/ui/src/tokens/tokens.ts
 */

export const tokens = {
  colors: {
    white: '#ffffff',
    black: '#000000',
    neutral: {
      50: '#fafafa',
      100: '#f4f4f5',
      200: '#e4e4e7',
      300: '#d4d4d8',
      400: '#a1a1aa',
      500: '#71717a',
      600: '#52525b',
      700: '#3f3f46',
      800: '#27272a',
      900: '#18181b',
      950: '#09090b',
    },
    bg: {
      default: 'var(--ro-color-bg)',
      subtle: 'var(--ro-color-bg-subtle)',
      inverse: 'var(--ro-color-bg-inverse)',
    },
    surface: {
      default: 'var(--ro-color-surface)',
      hover: 'var(--ro-color-surface-hover)',
      subtle: 'var(--ro-color-surface-subtle)',
      elevated: 'var(--ro-color-surface-elevated)',
    },
    focus: 'var(--ro-color-focus)',
    border: {
      default: 'var(--ro-color-border)',
      subtle: 'var(--ro-color-border-subtle)',
      strong: 'var(--ro-color-border-strong)',
    },
    text: {
      primary: 'var(--ro-color-text-primary)',
      secondary: 'var(--ro-color-text-secondary)',
      tertiary: 'var(--ro-color-text-tertiary)',
      inverse: 'var(--ro-color-text-inverse)',
    },
    status: {
      success: {
        default: 'var(--ro-color-success)',
        subtle: 'var(--ro-color-success-subtle)',
        border: 'var(--ro-color-success-border)',
        text: 'var(--ro-color-success-text)',
      },
      error: {
        default: 'var(--ro-color-error)',
        subtle: 'var(--ro-color-error-subtle)',
        border: 'var(--ro-color-error-border)',
        text: 'var(--ro-color-error-text)',
      },
      warning: {
        default: 'var(--ro-color-warning)',
        subtle: 'var(--ro-color-warning-subtle)',
        border: 'var(--ro-color-warning-border)',
        text: 'var(--ro-color-warning-text)',
      },
      info: {
        default: 'var(--ro-color-info)',
        subtle: 'var(--ro-color-info-subtle)',
        border: 'var(--ro-color-info-border)',
        text: 'var(--ro-color-info-text)',
      },
    },
    brand: {
      primary: 'var(--ro-color-primary)',
      primaryHover: 'var(--ro-color-primary-hover)',
      primarySubtle: 'var(--ro-color-primary-subtle)',
      secondary: 'var(--ro-color-secondary)',
      secondaryHover: 'var(--ro-color-secondary-hover)',
      accent: 'var(--ro-color-accent)',
    },
  },
  typography: {
    fonts: {
      sans: 'var(--ro-font-sans)',
      mono: 'var(--ro-font-mono)',
    },
    sizes: {
      xs: 'var(--ro-font-size-xs)',
      sm: 'var(--ro-font-size-sm)',
      base: 'var(--ro-font-size-base)',
      md: 'var(--ro-font-size-md)',
      lg: 'var(--ro-font-size-lg)',
      xl: 'var(--ro-font-size-xl)',
      '2xl': 'var(--ro-font-size-2xl)',
      '3xl': 'var(--ro-font-size-3xl)',
      '4xl': 'var(--ro-font-size-4xl)',
    },
    weights: {
      regular: 'var(--ro-font-weight-regular)',
      medium: 'var(--ro-font-weight-medium)',
      semibold: 'var(--ro-font-weight-semibold)',
      bold: 'var(--ro-font-weight-bold)',
    },
    lineHeights: {
      none: 'var(--ro-line-height-none)',
      tight: 'var(--ro-line-height-tight)',
      snug: 'var(--ro-line-height-snug)',
      normal: 'var(--ro-line-height-normal)',
      relaxed: 'var(--ro-line-height-relaxed)',
    },
  },
  spacing: {
    0: 'var(--ro-space-0)',
    1: 'var(--ro-space-1)',
    2: 'var(--ro-space-2)',
    3: 'var(--ro-space-3)',
    4: 'var(--ro-space-4)',
    5: 'var(--ro-space-5)',
    6: 'var(--ro-space-6)',
    8: 'var(--ro-space-8)',
    10: 'var(--ro-space-10)',
    12: 'var(--ro-space-12)',
    16: 'var(--ro-space-16)',
  },
  radius: {
    none: 'var(--ro-radius-none)',
    xs: 'var(--ro-radius-xs)',
    sm: 'var(--ro-radius-sm)',
    md: 'var(--ro-radius-md)',
    lg: 'var(--ro-radius-lg)',
    xl: 'var(--ro-radius-xl)',
    '2xl': 'var(--ro-radius-2xl)',
    full: 'var(--ro-radius-full)',
  },
  shadows: {
    none: 'var(--ro-shadow-none)',
    xs: 'var(--ro-shadow-xs)',
    sm: 'var(--ro-shadow-sm)',
    md: 'var(--ro-shadow-md)',
    lg: 'var(--ro-shadow-lg)',
    xl: 'var(--ro-shadow-xl)',
  },
  zIndex: {
    base: 'var(--ro-z-base)',
    raised: 'var(--ro-z-raised)',
    dropdown: 'var(--ro-z-dropdown)',
    sticky: 'var(--ro-z-sticky)',
    fixed: 'var(--ro-z-fixed)',
    backdrop: 'var(--ro-z-backdrop)',
    modal: 'var(--ro-z-modal)',
    popover: 'var(--ro-z-popover)',
    toast: 'var(--ro-z-toast)',
    tooltip: 'var(--ro-z-tooltip)',
  },
  motion: {
    durations: {
      instant: 'var(--ro-duration-instant)',
      fast: 'var(--ro-duration-fast)',
      normal: 'var(--ro-duration-normal)',
      slow: 'var(--ro-duration-slow)',
    },
    easings: {
      standard: 'var(--ro-ease-standard)',
      in: 'var(--ro-ease-in)',
      out: 'var(--ro-ease-out)',
      inOut: 'var(--ro-ease-in-out)',
    },
    transitions: {
      fast: 'var(--ro-transition-fast)',
      normal: 'var(--ro-transition-normal)',
    },
  },
  touchTargets: {
    min: 'var(--ro-touch-target-min)',
    dense: 'var(--ro-touch-target-dense)',
  },
  safeArea: {
    top: 'var(--ro-safe-area-top)',
    right: 'var(--ro-safe-area-right)',
    bottom: 'var(--ro-safe-area-bottom)',
    left: 'var(--ro-safe-area-left)',
  },
} as const;
