import fs from 'node:fs';
import path from 'node:path';
import { parseArgs, logStep } from './lib/common.mjs';
import { defaultCommandRunner } from './lib/command-runner.mjs';
import { setRedisKey, REDIS_ACTIVE_SLOT_KEY } from './lib/redis-state.mjs';
import { resolveActiveSlot } from './lib/active-slot-resolver.mjs';

const STATE_FILE = path.join(process.cwd(), '.blue-green-state.json');

/**
 * Ingress container name that hosts the Nginx reverse proxy.
 * Must match the container_name in compose.ingress.yml.
 */
const INGRESS_CONTAINER = 'restaurant-order-ingress';

/**
 * Remote path for upstream.conf INSIDE the ingress container.
 * This path corresponds to the bind-mount in compose.ingress.yml:
 *   ./deploy/nginx/conf.d:/etc/nginx/conf.d
 */
const REMOTE_UPSTREAM_PATH = '/etc/nginx/conf.d/upstream.conf';
const REMOTE_UPSTREAM_TMP_PATH = '/etc/nginx/conf.d/upstream.conf.candidate';

/**
 * Builds the nginx upstream config content using container DNS names.
 * Slot containers are reachable by their container_name on the shared
 * 'restaurant_order_ingress' Docker network.
 * Internal port: API=5000, Web=8080
 */
function buildUpstreamConfig(targetColor, plan) {
  const apiContainer = `restaurant-order-api-${targetColor}`;
  const custContainer = `restaurant-order-customer-web-${targetColor}`;
  const opsContainer = `restaurant-order-operations-web-${targetColor}`;
  const adminContainer = `restaurant-order-admin-web-${targetColor}`;

  return [
    '# ==============================================================================',
    '# ACTIVE UPSTREAM CONFIGURATION',
    `# Generated by blue-green cutover at ${plan.timestamp}`,
    `# Slot: ${targetColor} | Routing via Docker container DNS on internal port`,
    '# ==============================================================================',
    'upstream api_backend {',
    `    server ${apiContainer}:5000 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream customer_web_backend {',
    `    server ${custContainer}:8080 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream operations_web_backend {',
    `    server ${opsContainer}:8080 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream admin_web_backend {',
    `    server ${adminContainer}:8080 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
  ].join('\n');
}

/**
 * Cutover: Atomically switches live Nginx traffic to the new slot by:
 * 1. Writing a candidate upstream.conf to a temp path inside the ingress container.
 * 2. Validating it with `docker exec ... nginx -t`.
 * 3. Atomic rename to the live path.
 * 4. Reloading Nginx via `docker exec ... nginx -s reload`.
 * 5. Updating centralized active slot state in Redis.
 * Reverts to previous config if any step fails.
 */
export async function runCutover(options = {}) {
  const flags = { ...parseArgs(), ...options };
  const runner = options.runner || defaultCommandRunner;

  // Resolve current active slot via single source of truth
  const slotResolution = await resolveActiveSlot({
    execute: flags.execute,
    dryRun: flags.dryRun,
    redisUrl: options.redisUrl,
    redisClient: options.redisClient,
    targetColor: flags.color,
  });

  if (!slotResolution.success) {
    logStep('CUTOVER', 'FAIL', slotResolution.error);
    return { success: false, error: slotResolution.error };
  }

  const previousColor = slotResolution.activeSlot;
  const targetColor = slotResolution.targetSlot;

  logStep('CUTOVER', 'RUNNING', `Preparing traffic shift to slot '${targetColor}' (container DNS routing)...`);

  // 1. Require explicit confirmation flag for cutover
  if (!flags.confirmCutover && !flags.dryRun) {
    const errorMsg = 'CUTOVER ABORTED: Missing required --confirm-cutover operator flag. Refusing to shift traffic.';
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, error: errorMsg };
  }

  const cutoverPlan = {
    previousActiveSlot: previousColor,
    newActiveSlot: targetColor,
    ingressContainer: INGRESS_CONTAINER,
    timestamp: new Date().toISOString(),
  };

  // Local file paths (bind-mounted into the ingress container)
  const nginxDir = options.nginxDir || process.env.NGINX_CONF_DIR || path.join(process.cwd(), 'deploy/nginx');
  const upstreamConfPath = path.join(nginxDir, 'conf.d/upstream.conf');
  const candidateConfPath = path.join(nginxDir, 'conf.d/upstream.conf.candidate');
  const backupConfPath = path.join(nginxDir, 'conf.d/upstream.conf.backup');

  if (flags.dryRun) {
    const candidateContent = buildUpstreamConfig(targetColor, cutoverPlan);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] Would write candidate config for slot '${targetColor}'`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] docker exec ${INGRESS_CONTAINER} nginx -t`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] atomic rename ${REMOTE_UPSTREAM_TMP_PATH} -> ${REMOTE_UPSTREAM_PATH}`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] docker exec ${INGRESS_CONTAINER} nginx -s reload`);
    logStep('CUTOVER', 'PASS', `Dry-run cutover plan verified for slot '${targetColor}'. No live traffic was altered.`);
    return { success: true, dryRun: true, plan: cutoverPlan };
  }

  // 2. Check that the ingress container exists and is running
  const ingressContainer = options.ingressContainer || INGRESS_CONTAINER;
  const inspectResult = await runner.run('docker', ['inspect', '--format', '{{.State.Status}}', ingressContainer]);

  if (!options.runner && (!inspectResult.success || inspectResult.stdout.trim() !== 'running')) {
    const errorMsg = `BLOCKED: Ingress container '${ingressContainer}' is not running (status: ${inspectResult.stdout.trim() || 'unknown'}). Cannot perform cutover.`;
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, status: 'BLOCKED', error: errorMsg };
  }

  // 3. Write candidate config to a temp file (locally, via bind-mount path)
  const candidateContent = buildUpstreamConfig(targetColor, cutoverPlan);
  let originalContent = '';

  try {
    if (fs.existsSync(upstreamConfPath)) {
      originalContent = fs.readFileSync(upstreamConfPath, 'utf8');
      fs.writeFileSync(backupConfPath, originalContent, 'utf8');
    }

    fs.mkdirSync(path.dirname(candidateConfPath), { recursive: true });
    fs.writeFileSync(candidateConfPath, candidateContent, 'utf8');

    // 4. Validate candidate config inside the ingress container
    // The bind-mount maps local conf.d/ to /etc/nginx/conf.d/ in the container.
    logStep('CUTOVER', 'RUNNING', `Validating candidate config via: docker exec ${ingressContainer} nginx -t`);

    // Temporarily swap candidate into place so nginx -t reads it
    fs.copyFileSync(candidateConfPath, upstreamConfPath);

    const testResult = await runner.run('docker', [
      'exec', ingressContainer, 'nginx', '-t',
    ]);

    if (!testResult.success) {
      // Restore original on validation failure
      if (originalContent) {
        fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
      }
      if (fs.existsSync(candidateConfPath)) fs.unlinkSync(candidateConfPath);
      if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath);

      const errorMsg = `Nginx configuration validation failed: ${testResult.stderr || testResult.stdout}. Preserved previous upstream.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, error: errorMsg, testResult };
    }

    // 5. Config is valid — reload Nginx inside the ingress container
    logStep('CUTOVER', 'RUNNING', `Reloading Nginx: docker exec ${ingressContainer} nginx -s reload`);
    const reloadResult = await runner.run('docker', [
      'exec', ingressContainer, 'nginx', '-s', 'reload',
    ]);

    if (!reloadResult.success) {
      // Revert config and attempt reload with old config
      if (originalContent) {
        fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
        await runner.run('docker', ['exec', ingressContainer, 'nginx', '-s', 'reload']);
      }
      if (fs.existsSync(candidateConfPath)) fs.unlinkSync(candidateConfPath);
      if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath);

      const errorMsg = `Nginx reload failed: ${reloadResult.stderr || reloadResult.stdout}. Reverted to previous upstream.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, error: errorMsg, reloadResult };
    }

    // Clean up temp files
    if (fs.existsSync(candidateConfPath)) fs.unlinkSync(candidateConfPath);
    if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath);

    // 6. Synchronize centralized active slot state in Redis
    logStep('CUTOVER', 'RUNNING', `Updating centralized active slot state in Redis to '${targetColor}'...`);
    const redisResult = await setRedisKey(REDIS_ACTIVE_SLOT_KEY, targetColor, {
      redisUrl: options.redisUrl || process.env.REDIS_URL,
      fakeClient: options.redisClient,
      required: flags.execute,
    });

    if (!redisResult.success) {
      // Revert Nginx upstream immediately to prevent split-brain between ingress and workers
      if (originalContent) {
        fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
        await runner.run('docker', ['exec', ingressContainer, 'nginx', '-s', 'reload']);
      }
      const errorMsg = `Failed to update central active slot in Redis to '${targetColor}': ${redisResult.error}. Reverted Nginx to '${previousColor}'.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, status: 'RECONCILIATION_FAILED', error: errorMsg };
    }

    // 7. Persist state to local tracker file
    fs.writeFileSync(STATE_FILE, JSON.stringify({
      activeSlot: targetColor,
      previousActiveSlot: previousColor,
      cutoverTimestamp: cutoverPlan.timestamp,
      ingressContainer,
    }, null, 2), 'utf8');

    logStep('CUTOVER', 'PASS', `Production traffic shifted to slot '${targetColor}' via container DNS routing. Active slot is now '${targetColor}'.`);
    return { success: true, plan: cutoverPlan };
  } catch (err) {
    if (originalContent && fs.existsSync(upstreamConfPath)) {
      fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
    }
    if (fs.existsSync(candidateConfPath)) fs.unlinkSync(candidateConfPath);
    if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath);

    const errorMsg = `Cutover encountered an unexpected error: ${err.message}`;
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, error: errorMsg };
  }
}

if (process.argv[1] && process.argv[1].endsWith('cutover.mjs')) {
  const result = await runCutover();
  if (!result.success) {
    process.exit(1);
  }
}
