import fs from 'node:fs';
import path from 'node:path';
import { parseArgs, logStep } from './lib/common.mjs';
import { defaultCommandRunner } from './lib/command-runner.mjs';
import { setRedisKey, REDIS_ACTIVE_SLOT_KEY } from './lib/redis-state.mjs';
import { resolveActiveSlot } from './lib/active-slot-resolver.mjs';

const DEFAULT_STATE_FILE = path.join(process.cwd(), '.blue-green-state.json');

/**
 * Ingress container name that hosts the Nginx reverse proxy.
 * Must match the container_name in compose.ingress.yml.
 */
const INGRESS_CONTAINER = 'restaurant-order-ingress';

/**
 * Builds the nginx upstream config content using container DNS names.
 * Slot containers are reachable by their container_name on the shared
 * 'restaurant_order_ingress' Docker network.
 * Internal port: API=5000, Web=8080
 */
export function buildUpstreamConfig(targetColor, plan) {
  const apiContainer = `restaurant-order-api-${targetColor}`;
  const custContainer = `restaurant-order-customer-web-${targetColor}`;
  const opsContainer = `restaurant-order-operations-web-${targetColor}`;
  const adminContainer = `restaurant-order-admin-web-${targetColor}`;

  return [
    '# ==============================================================================',
    '# ACTIVE UPSTREAM CONFIGURATION',
    `# Generated by blue-green cutover at ${plan.timestamp}`,
    `# Slot: ${targetColor} | Routing via Docker container DNS on internal port`,
    '# ==============================================================================',
    'upstream api_backend {',
    `    server ${apiContainer}:5000 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream customer_web_backend {',
    `    server ${custContainer}:8080 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream operations_web_backend {',
    `    server ${opsContainer}:8080 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream admin_web_backend {',
    `    server ${adminContainer}:8080 max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
  ].join('\n');
}

/**
 * Validates syntax of upstream configuration string.
 */
function validateConfigSyntax(content) {
  if (!content || typeof content !== 'string') return false;
  if (!content.includes('upstream api_backend {')) return false;
  if (!content.includes('upstream customer_web_backend {')) return false;
  if (!content.includes('upstream operations_web_backend {')) return false;
  if (!content.includes('upstream admin_web_backend {')) return false;
  const openBraces = (content.match(/{/g) || []).length;
  const closeBraces = (content.match(/}/g) || []).length;
  return openBraces > 0 && openBraces === closeBraces;
}

/**
 * Cutover: Atomically switches live Nginx traffic to the new slot by:
 * 1. Generating and syntactically validating candidate upstream config.
 * 2. Writing candidate to a temporary file (.candidate) on the same filesystem.
 * 3. Validating candidate config inside the ingress container WITHOUT altering live upstream.conf.
 * 4. Atomically renaming (.candidate -> upstream.conf) on the local filesystem.
 * 5. Reloading Nginx via `docker exec ... nginx -s reload`.
 * 6. If reload fails: atomically restoring backup, re-validating and reloading.
 * 7. Updating centralized active slot state in Redis and verifying read-back.
 * Reverts to previous config if any step fails.
 */
export async function runCutover(options = {}) {
  const flags = { ...parseArgs(), ...options };
  const runner = options.runner || defaultCommandRunner;
  const renameFile = options.renameFn || fs.renameSync;
  const stateFile = options.stateFile || DEFAULT_STATE_FILE;

  // Resolve current active slot via single source of truth
  const slotResolution = await resolveActiveSlot({
    execute: flags.execute,
    dryRun: flags.dryRun,
    redisUrl: options.redisUrl,
    redisClient: options.redisClient,
    targetColor: flags.color,
  });

  if (!slotResolution.success) {
    logStep('CUTOVER', 'FAIL', slotResolution.error);
    return { success: false, error: slotResolution.error };
  }

  const previousColor = slotResolution.activeSlot;
  const targetColor = slotResolution.targetSlot;

  logStep('CUTOVER', 'RUNNING', `Preparing traffic shift to slot '${targetColor}' (container DNS routing)...`);

  // 1. Require explicit confirmation flag for cutover in execute mode
  if (!flags.confirmCutover && !flags.dryRun) {
    const errorMsg = 'CUTOVER ABORTED: Missing required --confirm-cutover operator flag. Refusing to shift traffic.';
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, error: errorMsg };
  }

  const cutoverPlan = {
    previousActiveSlot: previousColor,
    newActiveSlot: targetColor,
    ingressContainer: INGRESS_CONTAINER,
    timestamp: new Date().toISOString(),
  };

  // Local file paths (bind-mounted into the ingress container)
  const nginxDir = options.nginxDir || process.env.NGINX_CONF_DIR || path.join(process.cwd(), 'deploy/nginx');
  const confD = path.join(nginxDir, 'conf.d');
  const upstreamConfPath = path.join(confD, 'upstream.conf');
  const candidateConfPath = path.join(confD, 'upstream.conf.candidate');
  const backupConfPath = path.join(confD, 'upstream.conf.backup');
  const validateHarnessPath = path.join(confD, '.nginx-validate.conf.tmp');

  const cleanupTempFiles = () => {
    try { if (fs.existsSync(candidateConfPath)) fs.unlinkSync(candidateConfPath); } catch {}
    try { if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath); } catch {}
    try { if (fs.existsSync(validateHarnessPath)) fs.unlinkSync(validateHarnessPath); } catch {}
  };

  if (flags.dryRun) {
    const candidateContent = buildUpstreamConfig(targetColor, cutoverPlan);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] Would write candidate config for slot '${targetColor}'`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] docker exec ${INGRESS_CONTAINER} nginx -t`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] atomic rename ${candidateConfPath} -> ${upstreamConfPath}`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] docker exec ${INGRESS_CONTAINER} nginx -s reload`);
    logStep('CUTOVER', 'PASS', `Dry-run cutover plan verified for slot '${targetColor}'. No live traffic was altered.`);
    return { success: true, dryRun: true, plan: cutoverPlan };
  }

  // 2. Check that the ingress container exists and is running
  const ingressContainer = options.ingressContainer || INGRESS_CONTAINER;
  const inspectResult = await runner.run('docker', ['inspect', '--format', '{{.State.Status}}', ingressContainer]);

  if (!options.runner && (!inspectResult.success || inspectResult.stdout.trim() !== 'running')) {
    const errorMsg = `BLOCKED: Ingress container '${ingressContainer}' is not running (status: ${inspectResult.stdout?.trim() || 'unknown'}). Cannot perform cutover.`;
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, status: 'BLOCKED', error: errorMsg };
  }

  // 3. Build & syntactically validate candidate config
  const candidateContent = options.candidateContentOverride || buildUpstreamConfig(targetColor, cutoverPlan);
  if (!validateConfigSyntax(candidateContent)) {
    const errorMsg = 'Candidate upstream configuration syntax is invalid! Aborting before filesystem modification.';
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, error: errorMsg };
  }

  const hasOriginal = fs.existsSync(upstreamConfPath);
  let originalContent = '';

  try {
    fs.mkdirSync(confD, { recursive: true });

    if (hasOriginal) {
      originalContent = fs.readFileSync(upstreamConfPath, 'utf8');
      fs.writeFileSync(backupConfPath, originalContent, 'utf8');
    }

    // Write candidate config to isolated temp file on the SAME filesystem
    fs.writeFileSync(candidateConfPath, candidateContent, 'utf8');

    // 4. Validate candidate config inside the ingress container WITHOUT touching live upstream.conf
    fs.writeFileSync(validateHarnessPath, [
      'events { worker_connections 1024; }',
      'http {',
      '    include /etc/nginx/conf.d/upstream.conf.candidate;',
      '    server {',
      '        listen 80;',
      '        location / { proxy_pass http://api_backend; }',
      '    }',
      '}',
      '',
    ].join('\n'), 'utf8');

    logStep('CUTOVER', 'RUNNING', `Validating candidate config via: docker exec ${ingressContainer} nginx -t`);
    const testResult = await runner.run('docker', [
      'exec', ingressContainer, 'nginx', '-t', '-c', '/etc/nginx/conf.d/.nginx-validate.conf.tmp',
    ]);

    if (!testResult.success) {
      cleanupTempFiles();
      const errorMsg = `Nginx configuration validation failed: ${testResult.stderr || testResult.stdout}. Preserved previous upstream.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, error: errorMsg, testResult };
    }

    // 5. Candidate is verified — perform ATOMIC rename on local filesystem
    try {
      renameFile(candidateConfPath, upstreamConfPath);
    } catch (renameErr) {
      cleanupTempFiles();
      const errorMsg = `Atomic rename failed: ${renameErr.message}. Live upstream untouched.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, error: errorMsg };
    }

    // 6. Reload Nginx inside the ingress container
    logStep('CUTOVER', 'RUNNING', `Reloading Nginx: docker exec ${ingressContainer} nginx -s reload`);
    const reloadResult = await runner.run('docker', [
      'exec', ingressContainer, 'nginx', '-s', 'reload',
    ]);

    if (!reloadResult.success) {
      // Revert config atomically from backup and reload
      if (hasOriginal) {
        try {
          renameFile(backupConfPath, upstreamConfPath);
        } catch {
          fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
        }

        const restoreTest = await runner.run('docker', ['exec', ingressContainer, 'nginx', '-t']);
        const restoreReload = await runner.run('docker', ['exec', ingressContainer, 'nginx', '-s', 'reload']);

        cleanupTempFiles();

        if (!restoreTest.success || !restoreReload.success) {
          const critMsg = `CRITICAL_INCONSISTENT_STATE: Initial reload failed (${reloadResult.stderr || reloadResult.stdout}) AND restoration reload failed (${restoreReload.stderr || restoreReload.stdout})! Ingress upstream is broken.`;
          logStep('CUTOVER', 'FAIL', critMsg);
          return { success: false, status: 'CRITICAL_INCONSISTENT_STATE', error: critMsg };
        }
      } else {
        try { fs.unlinkSync(upstreamConfPath); } catch {}
        cleanupTempFiles();
      }

      const errorMsg = `Nginx reload failed: ${reloadResult.stderr || reloadResult.stdout}. Reverted to previous upstream.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, error: errorMsg, reloadResult };
    }

    // Clean up backup now that reload succeeded
    cleanupTempFiles();

    // 7. Synchronize centralized active slot state in Redis
    logStep('CUTOVER', 'RUNNING', `Updating centralized active slot state in Redis to '${targetColor}'...`);
    const redisResult = await setRedisKey(REDIS_ACTIVE_SLOT_KEY, targetColor, {
      redisUrl: options.redisUrl || process.env.REDIS_URL,
      fakeClient: options.redisClient,
      required: flags.execute,
    });

    if (!redisResult.success) {
      // Revert Nginx upstream immediately to prevent split-brain between ingress and workers
      if (hasOriginal) {
        fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
        const revertReload = await runner.run('docker', ['exec', ingressContainer, 'nginx', '-s', 'reload']);
        if (!revertReload.success) {
          const critMsg = `CRITICAL_INCONSISTENT_STATE: Failed to update central Redis active slot (${redisResult.error}) and Nginx revert reload also failed!`;
          logStep('CUTOVER', 'FAIL', critMsg);
          return { success: false, status: 'CRITICAL_INCONSISTENT_STATE', error: critMsg };
        }
      }
      const errorMsg = `Failed to update central active slot in Redis to '${targetColor}': ${redisResult.error}. Reverted Nginx to '${previousColor}'.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, status: 'RECONCILIATION_FAILED', error: errorMsg };
    }

    // 8. Verify Redis read-back parity
    if (flags.execute && options.redisClient) {
      const readBack = await options.redisClient.get(REDIS_ACTIVE_SLOT_KEY);
      if (!readBack.success || readBack.value !== targetColor) {
        if (hasOriginal) {
          fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
          await runner.run('docker', ['exec', ingressContainer, 'nginx', '-s', 'reload']);
        }
        const errorMsg = `Redis read-back verification mismatch: expected '${targetColor}', got '${readBack.value || 'null'}'. Reverted Nginx.`;
        logStep('CUTOVER', 'FAIL', errorMsg);
        return { success: false, status: 'RECONCILIATION_FAILED', error: errorMsg };
      }
    }

    // 9. Persist state to local tracker file
    fs.writeFileSync(stateFile, JSON.stringify({
      activeSlot: targetColor,
      previousActiveSlot: previousColor,
      cutoverTimestamp: cutoverPlan.timestamp,
      ingressContainer,
    }, null, 2), 'utf8');

    logStep('CUTOVER', 'PASS', `Production traffic shifted to slot '${targetColor}' via container DNS routing. Active slot is now '${targetColor}'.`);
    return { success: true, plan: cutoverPlan };
  } catch (err) {
    cleanupTempFiles();
    if (hasOriginal && fs.existsSync(upstreamConfPath)) {
      fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
    }
    const errorMsg = `Cutover encountered an unexpected error: ${err.message}`;
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, error: errorMsg };
  }
}

if (process.argv[1] && process.argv[1].endsWith('cutover.mjs')) {
  const result = await runCutover();
  if (!result.success) {
    process.exit(1);
  }
}
