import fs from 'node:fs';
import path from 'node:path';
import { parseArgs, logStep } from './lib/common.mjs';
import { defaultCommandRunner } from './lib/command-runner.mjs';
import { setRedisKey, REDIS_ACTIVE_SLOT_KEY } from './lib/redis-state.mjs';

const STATE_FILE = path.join(process.cwd(), '.deployment-state.json');

/**
 * Cutover: Switches ingress / load balancer traffic to the newly deployed slot.
 * Atomically updates Nginx upstream configuration, validates via `nginx -t`,
 * reloads Nginx, and updates `.deployment-state.json`.
 */
export async function runCutover(options = {}) {
  const flags = parseArgs(process.argv.slice(2), options);
  const runner = options.runner || defaultCommandRunner;
  const targetColor = (flags.color || 'green').toLowerCase();
  const previousColor = targetColor === 'blue' ? 'green' : 'blue';
  const targetPort = targetColor === 'blue'
    ? (process.env.API_PORT_BLUE || 5001)
    : (process.env.API_PORT_GREEN || 5002);
  const targetCustPort = targetColor === 'blue'
    ? (process.env.CUSTOMER_WEB_PORT_BLUE || 3001)
    : (process.env.CUSTOMER_WEB_PORT_GREEN || 3011);
  const targetOpsPort = targetColor === 'blue'
    ? (process.env.OPERATIONS_WEB_PORT_BLUE || 3002)
    : (process.env.OPERATIONS_WEB_PORT_GREEN || 3012);
  const targetAdminPort = targetColor === 'blue'
    ? (process.env.ADMIN_WEB_PORT_BLUE || 3003)
    : (process.env.ADMIN_WEB_PORT_GREEN || 3013);

  logStep('CUTOVER', 'RUNNING', `Preparing traffic shift to slot '${targetColor}' (port ${targetPort})...`);

  // 1. Require explicit confirmation flag for cutover
  if (!flags.confirmCutover && !flags.dryRun) {
    const errorMsg = 'CUTOVER ABORTED: Missing required --confirm-cutover operator flag. Refusing to shift traffic.';
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, error: errorMsg };
  }

  const cutoverPlan = {
    previousActiveSlot: previousColor,
    newActiveSlot: targetColor,
    targetPort: Number(targetPort),
    targetCustPort: Number(targetCustPort),
    targetOpsPort: Number(targetOpsPort),
    targetAdminPort: Number(targetAdminPort),
    timestamp: new Date().toISOString(),
  };

  const nginxDir = options.nginxDir || process.env.NGINX_CONF_DIR || path.join(process.cwd(), 'deploy/nginx');
  const mainConfPath = path.join(nginxDir, 'nginx.conf');
  const upstreamConfPath = path.join(nginxDir, 'conf.d/upstream.conf');
  const backupConfPath = path.join(nginxDir, 'conf.d/upstream.conf.backup');

  if (flags.dryRun) {
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] Updating Nginx upstream: server 127.0.0.1:${targetPort} (${targetColor})`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] Validating config via 'nginx -t -c ${mainConfPath}'`);
    logStep('CUTOVER', 'DRY-RUN', `[SIMULATED] Reloading Nginx via 'nginx -s reload'`);
    logStep('CUTOVER', 'PASS', `Dry-run cutover plan verified for slot '${targetColor}'. No live traffic was altered.`);
    return { success: true, dryRun: true, plan: cutoverPlan };
  }

  // 2. Check ingress provider availability
  const ingressProvider = options.ingressProvider || process.env.INGRESS_PROVIDER || 'nginx';
  if (ingressProvider === 'none' || (!options.runner && !fs.existsSync(mainConfPath))) {
    const errorMsg = 'BLOCKED: Ingress provider is not configured or nginx config is missing. Refusing to claim success without verified ingress.';
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, status: 'BLOCKED', error: errorMsg };
  }

  // 3. Prepare candidate upstream configuration
  const candidateContent = [
    '# ==============================================================================',
    '# ACTIVE UPSTREAM CONFIGURATION',
    `# Generated by blue-green cutover at ${cutoverPlan.timestamp}`,
    `# Slot: ${targetColor} | API: ${targetPort} | Customer: ${targetCustPort} | Ops: ${targetOpsPort} | Admin: ${targetAdminPort}`,
    '# ==============================================================================',
    'upstream api_backend {',
    `    server 127.0.0.1:${targetPort} max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream customer_web_backend {',
    `    server 127.0.0.1:${targetCustPort} max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream operations_web_backend {',
    `    server 127.0.0.1:${targetOpsPort} max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
    'upstream admin_web_backend {',
    `    server 127.0.0.1:${targetAdminPort} max_fails=3 fail_timeout=10s;`,
    '    keepalive 32;',
    '}',
    '',
  ].join('\n');

  // 4. Atomic swap with rollback on failure
  let originalContent = '';
  try {
    if (fs.existsSync(upstreamConfPath)) {
      originalContent = fs.readFileSync(upstreamConfPath, 'utf8');
      fs.writeFileSync(backupConfPath, originalContent, 'utf8');
    }

    // Write new configuration
    fs.mkdirSync(path.dirname(upstreamConfPath), { recursive: true });
    fs.writeFileSync(upstreamConfPath, candidateContent, 'utf8');

    // 5. Validate with nginx -t
    logStep('CUTOVER', 'RUNNING', `Validating Nginx configuration with 'nginx -t'...`);
    const testResult = await runner.run('nginx', ['-t', '-c', mainConfPath]);

    if (!testResult.success) {
      // Revert to backup immediately
      if (originalContent) {
        fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
      }
      if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath);

      const errorMsg = `Nginx configuration validation failed ('nginx -t'): ${testResult.stderr || testResult.stdout}. Preserved previous upstream.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, error: errorMsg, testResult };
    }

    // 6. Reload Nginx
    logStep('CUTOVER', 'RUNNING', `Reloading Nginx with 'nginx -s reload'...`);
    const reloadResult = await runner.run('nginx', ['-s', 'reload']);

    if (!reloadResult.success) {
      // Revert to backup immediately
      if (originalContent) {
        fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
        await runner.run('nginx', ['-s', 'reload']);
      }
      if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath);

      const errorMsg = `Nginx reload failed: ${reloadResult.stderr || reloadResult.stdout}. Restored previous configuration.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      return { success: false, error: errorMsg, reloadResult };
    }

    // Clean up backup file
    if (fs.existsSync(backupConfPath)) {
      fs.unlinkSync(backupConfPath);
    }

    // 7. Update centralized active slot state in Redis
    logStep('CUTOVER', 'RUNNING', `Updating centralized active slot state in Redis to '${targetColor}'...`);
    const redisResult = await setRedisKey(REDIS_ACTIVE_SLOT_KEY, targetColor, {
      redisUrl: options.redisUrl || process.env.REDIS_URL,
      fakeClient: options.redisClient,
      required: flags.execute,
    });

    if (!redisResult.success) {
      // Revert Nginx to maintain state consistency
      const errorMsg = `Central Redis state update failed: ${redisResult.error}. Reverting Nginx configuration.`;
      logStep('CUTOVER', 'FAIL', errorMsg);
      if (originalContent) {
        fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
        await runner.run('nginx', ['-s', 'reload']);
      }
      return { success: false, error: errorMsg };
    }

    // 8. Persist active state to file
    fs.writeFileSync(STATE_FILE, JSON.stringify(cutoverPlan, null, 2), 'utf8');

    logStep('CUTOVER', 'PASS', `Production traffic shifted to slot '${targetColor}' on port ${targetPort}. Active slot is now '${targetColor}'.`);
    return { success: true, dryRun: false, plan: cutoverPlan };
  } catch (err) {
    if (originalContent && fs.existsSync(upstreamConfPath)) {
      fs.writeFileSync(upstreamConfPath, originalContent, 'utf8');
    }
    if (fs.existsSync(backupConfPath)) fs.unlinkSync(backupConfPath);

    const errorMsg = `Cutover failed with unexpected exception: ${err.message}`;
    logStep('CUTOVER', 'FAIL', errorMsg);
    return { success: false, error: errorMsg };
  }
}

if (process.argv[1] && process.argv[1].endsWith('cutover.mjs')) {
  const result = await runCutover();
  if (!result.success) {
    process.exit(1);
  }
}
